language: java
notifications:
  email:
    recipients:
      - akamen@blackducksoftware.com
      - jrichard@blackducksoftware.com
      
install: true
script:
- mvn install -DskipTests=true
- mvn test
